# Support for AppVeyor CI -- https://www.appveyor.com/
# Copyright (C) Markus Franz Xaver Johannes Oberhumer

os: Visual Studio 2015

environment:
  global: { TRAVIS_OS_NAME: windows, C: "", B: release, CROSS: "", ALLOW_FAIL: "" }
  matrix:
    - { C: gcc-m32 }
    - { C: gcc-m64 }
#    - { C: msvc-14.0-x64, CL_VERSION: 19.00, VS_VERSION: 2015 }

init:
  - git config --global core.autocrlf input
  - dir "c:\Program Files\Git\usr\bin"
  - dir "c:\cygwin\bin"
  - dir "c:\mingw\bin"
  - dir "c:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin"

install:
  - where bash
  - where cat
  - where git
  - cd c:\projects
  - md build build\%C% deps
  - cd c:\projects\upx
  - git submodule update --init --recursive
  - cd c:\projects\deps
  - curl -q -L --retry 5 -o ucl-1.03.tar.gz   "https://github.com/upx/upx/files/499379/ucl-1.03.tar.gz"
  - curl -q -L --retry 5 -o zlib-1.2.8.tar.gz "https://github.com/upx/upx/files/499381/zlib-1.2.8.tar.gz"
  - tar -xzf ucl-1.03.tar.gz
##- curl -q -L --retry 5 -o config.guess "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD"
##- curl -q -L --retry 5 -o config.sub   "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD"
##- cp config.guess config.sub ucl-1.03/acconfig/
  # patch UCL for msvc-14.0 (vsnprintf issue)
  - sed -i '/# *define.*snprintf  *_v*snprintf$/d' ucl-1.03/acc/acc_auto.h
  - tar -xzf zlib-1.2.8.tar.gz
  - git clone https://github.com/upx/upx-testsuite
##  - if "%C%"=="gcc-m32" set PATH=c:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
  - if "%C%"=="msvc-10.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-10.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64 )
  - if "%C%"=="msvc-11.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-11.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat" amd64 )
  - if "%C%"=="msvc-12.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-12.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64 )
  - if "%C%"=="msvc-14.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-14.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 )

build_script:
  - cd c:\projects\upx
  - if "%C%"=="gcc-m32" set PATH=c:\cygwin\bin;%PATH%
  - if "%C%"=="gcc-m32" bash -x ./.github/travis_build.sh
  - if "%C%"=="gcc-m64" set PATH=c:\cygwin\bin;%PATH%
  - if "%C%"=="gcc-m64" bash -x ./.github/travis_build.sh

test_script:
  - cd c:\projects\upx
  - bash ./.github/travis_testsuite_1.sh

# vim:set ts=2 sw=2 et:
