# Support for Travis CI -- https://travis-ci.org/upx/upx/builds
# Copyright (C) Markus Franz Xaver Johannes Oberhumer

sudo: false
language: cpp

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - devel
    - travis

addons:
  sources: &S
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    - llvm-toolchain-precise-3.6
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise-3.8

env:
  global:
    - C= B= CROSS= ALLOW_FAIL=
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - os: linux
      compiler: gcc
      env: C=gcc-4.6 CROSS=arm-linux
      addons: { apt: { packages: [ "gcc-arm-linux-gnueabi", "qemu-user-static" ] } }
    - os: linux
      compiler: gcc
      env: C=gcc-4.6 CROSS=mips-linux
      addons: { apt: { packages: [ "gcc-mips-linux-gnu", "qemu-user" ] } }
    - os: linux
      compiler: gcc
      env: C=gcc-4.6-m32 CROSS=i386-win32.mingw
      addons: { apt: { packages: [ "gcc-mingw-w64-i686" ] } }
    - os: linux
      compiler: gcc
      env: C=gcc-4.6-m64 CROSS=x86_64-win64.mingw
      addons: { apt: { packages: [ "gcc-mingw-w64-x86_64" ] } }

install:
  - dpkg -L qemu-user || true
  - dpkg -L qemu-user-static || true
  - dpkg -L gcc-mips-linux-gnu || true
  - dpkg -L gcc-ppc-linux-gnu || true
  - umask 022; cd $TRAVIS_BUILD_DIR && mkdir -p ../deps
  - cd ../deps && travis_retry wget -q -O - https://github.com/upx/upx/files/499379/ucl-1.03.tar.gz | tar -xz
  - cd ../deps && travis_retry git clone https://github.com/upx/upx-testsuite
  - |
    cd /
    if [[ $TRAVIS_OS_NAME == linux ]]; then
      if [[ $B =~ (^|\+)coverage($|\+) ]]; then
        travis_retry pip install --user cpp-coveralls
      fi
    fi
    if [[ $TRAVIS_OS_NAME == osx ]]; then
      if ! gsha256sum </bin/sh >/dev/null 2>/dev/null; then travis_retry brew install coreutils; fi
      if [[ $B =~ (^|\+)coverage($|\+) ]]; then
        travis_retry brew install lcov
        travis_retry pip install --user cpp-coveralls
      fi
    fi

script:
  - cd $TRAVIS_BUILD_DIR && bash ./.github/travis_build.sh
  - cd $TRAVIS_BUILD_DIR && bash ./.github/travis_testsuite_1.sh

# vim:set ts=2 sw=2 et:
